controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]

    wheel_separation: 0.45
    wheel_radius: 0.1

    use_stamped_vel: false
    base_frame_id: base_link
    publish_rate: 50.0
    open_loop: true

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.0]

    enable_odom_tf: true
    odom_frame_id: odom
    publish_limited_velocity: true
    velocity_rolling_window_size: 10